version: "3"

services:
  db:
    image: "postgres:14-alpine3.20"
    environment:
      POSTGRES_PASSWORD: 'mysecretpassword'
      POSTGRES_USER: "dummy"
      POSTGRES_DB: "test123"
    ports:
      - "8081:5432"
    volumes:
      - postresql:/var/lib/postgresql/data
    restart: always
volumes:
  postresql: